Magento 2.4.6 Support
easytranslate-com/laas-api-magento-2-plugin pull request #21
Opened 2023-05-19 15:00 UTC by sprankhub

2023-05-22 09:49 UTC, norgeindian requested changes

2023-05-22 09:49 UTC, norgeindian commented on .github/workflows/integration.yml
According to our docs and https://packagist.org/packages/magento/community-edition, the following tests are missing:

- 2.4.4-p2 with PHP 8.1
- 2.4.4-p3 with PHP 7.4
- 2.4.5-p1 with PHP 7.4
- 2.4.5-p1 with PHP 8.1
- 2.4.5-p2 with PHP 7.4
- 2.4.6 with PHP 8.2

Please add them or let me know why we should not include them.

2023-05-22 13:56 UTC, sprankhub commented on .github/workflows/integration.yml
- 2.4.4-p2 with PHP 8.1: Added.
- 2.4.4-p3 with PHP 7.4: Added.
- 2.4.5-p1 with PHP 7.4: Not possible, because Magento's core integration tests use PHP 8 features.
- 2.4.5-p1 with PHP 8.1: Added.
- 2.4.5-p2 with PHP 7.4: Not possible, because Magento's core integration tests use PHP 8 features.
- 2.4.6 with PHP 8.2: Not possible, because extdn does not support PHP 8.2 yet. See https://github.com/extdn/github-actions-m2/issues/86.

2023-05-23 10:12 UTC, norgeindian approved these changes

2023-05-23 13:19 UTC, merged